export const ADD_TOKEN = 'ADD_TOKEN';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const RESTAURANTS_LOADING = 'RESTAURANTS_LOADING';
export const RESTAURANTS_FAILED = 'RESTAURANTS_FAILED';
export const ADD_RESTAURANTS = 'ADD_RESTAURANTS';
export const ADD_ZIP = 'ADD_ZIP';